language: scala
scala:
- 2.12.7
- 2.11.12
jdk:
- oraclejdk8
ignore:
- version.sbt
- README.md
sudo: false
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.coursier"
  - "$HOME/.sbt"
env:
  global:
  - PUBLISH=true
  - secure: ivipIFC1MNht1FZTWGv8qS7s3Gas32QjOFdbRyTVrXC62lJj+uId6rsaVjrGV8q4b01suFkz5xr5ghfXUPIiV0eg+AJHrrqfa+Ovu0Da5aOx1H00erZ7yjhZeDt/Bj+J7WTN3j5opEgJKVtpj298PZwJfQghXRQGIjE/KkivPc0DI989RIaZoRxNQ4hODI6t7BRu2mlb30R7HBuXJtYIiPDF5HwhhVwa7rGRP7ngeGNE33bxP2oC7QWsLt7P+Ex7eade3WndSmWPev5NLF/L6VIf6AS4LKUcWpH3oJJ036G6dCcayD1lDLBYAaCFFazp9BGBYTQYPyyiKwRHuSohzCO9iuNVo4ro13WGq1HAYg58R6CYYjv/EESH57jm2V76okmfS7wwqLod1vtII30ZVI4ddPNvOHkQ860t8byeDG5MxBn40Z/ORyZR/fw/CaLGtDB1lEOYBuei7EnaYSVWbS/he96EIBOb+qIOpLDzbart4gfqBqevOHAW5AWtFz+ogsPdNZjTmIfAhlQ3wMO4m6n1Yut53WacD8IL7P/aE/Tq86+oyYXzNQ9JRUi//pTFW8n81MFs/7yCCnT97+PFriuo5hPeJqdE6YnKE9ofQWiABJqt2Rj8JU68OAhTpwZJ/Jv9OsmHRAqVMiAc8KKta8PW7/jaZBzBCUO6XD2J1vk=
  - secure: ovKkCEtq8JlGMgCxMpKKCVCV8hjNGzs27B3cIimoPGdOc4m6yi2bDZRlXl9EwFBkkweiYu5LsKQvo0JemNIHyt8vBzhIce0OF2gqya2Hx8/Hwqdd7WcXlP9tWqTYuwKRoouE6LaQOlAiNYz/BHF7h6YdFqBDfLV2OYAYDJRGe5dSDYv8vbuNfoD+rpwXiPAYhlzYDOrodAJrL8VqfNOP8RTWFWfbwOpkWGtx39X8J+Ypn2ed/J28Iy8LdBJ6+X0CZGYaWKlkoBmYLsvEOfxG73YFqMraWqXAXcmIiezrQVru8SMmhaZzr23I7HUs3/GAlNvcFtgjIUmCtVDQe1xRe6cO4an5Cv57iH7IUqF71ScO0+LBtE8n2XYFEk1sKEHUWIrJjd9ymrdRxFPONAdmjYVIh5dy9XVZymoDTBG2cifvyWx1+s+K0bd3k3SBieRhqxm9pMG2RcLIoyHTbT8F+VfXZSJQP3fUBym2JBRsJMaPjraY16poyPhNZXTl5sLdy8ix6WB0cKFrjzKpOto+yyvzQ+eFqaTUm/C9R3YU9ebVaFBBshGFK6ZIuJyXin0Mfs2bKzAZ4mB61KGGOK4xCddOR7NRwfrGH6Ja5vAm+xB/b4Dep4NWJZe2JiehviR7NYViGlJIQmxzEf7gqst35ejDolyIL6nwU0wnD/VBllo=
  - secure: J7FfpU/vHLWIzywUQzIrFQp8uAwuLQoKTzS4GszwB3F5SVgFMNKBXQ/rPKsue9aetSskumv/N3kfLpuBQBAmEWM1zGFqq358+pw437uNZYKREwFJN3/ozD5cmIvojMR6iei6iVusGZI5FP6/CFOcgctgId6ZJexPvQtwN4KxsDGrbwRegDgq1B6k3xlvVcmQ/iQyxmKYierXXHNkDrsmgV2iz0Pk5833oBpHmMKoEfTz5Jb7hlehqjkcXVd/KI5JGNq8K2CkVVWr7KEaCMSOY6EKt25hwW7ZKHtnNQWi7ijkx8OkAaPjQoTVaWLnEquUq4YVsydVnwHrvKa/VYjqF1UHRZsvnCY9xUqjnqcA1wq3y8qrvd7I2q4XxaJbGz75PBtW5lLFswIuZsH5suYdiHbZC4VT5TngoyIdjEptsDxTfaOXDVNHh4cUXwuYa/oTdWxlkyrs+X3n7CtK0CzrnlVUQ/t7N60wENezPsXtgkl77OPLG1zo4DNQIssTqK+TUlusUlnGflGpWmzq+EJr94JvFmDK4jy+SY1j15Lw7+3uZ0V+bDLUnEoGPxWVLPuhJbIoGbu+d7l81TfYfDGbYKvDtsrsMHUHDE/oy0jl8xm7pK2R+aRuZY5BY0mbGef8xFK6ZeAcFqNMfEAM0nGCE5e9LAJccvBU92USdqG7Fhw=
  - secure: rBB/DwiKe2fVzkRL+Wd9KM76tb9lltmZOc0HKHRhvhGV56bgQCHQ4T/aIyxeKsunLuZlD37VW6cxrkZG9FT8tNXXb/kcMuqYupQ8SpEo+tu9rRjHPluFi45ZnzEsZG3WPYlSFXW6t7Rb4hYVFj5ru3CXDxgOfja0+ovx/l9Msx83Gn0OSSxDuDc8mcTg7KnXJGSKW808UVZbu+CPkJpuYYP2QF6cA4hR+vliMXeRXQjDNY/fwYsLk2J4T2NQ0O/u4qhH6V1Evq5pekY0p8wh1Jlm8v8iqCogooLSnT+QvCHvHFBrlx+YMQL46xnmJk6zTbTEmMwjzTt0lwUIw5mf9TCKjQdNt4L96/woFTutm/3SFN0Ol/X9m+zI/ROr+CuCRXnf/KISaM/YnRDaxqUt0O0XVUjOfSOQ2u88Rjqa3iYqssHqaZ4vGzrOzIhpeP/wJswpfPsh5iKRM7/L8rwm7FOnON8u6OAt6q9z3kCHwbyUGms0u/8BXjWk9hnUziKG5kSajTlyXVQwdF/0GlseBG/4w++FtwJODmTK6NK6ZN0mb0bMpDnxHF7jJM4crKo68UlNXroWokXnTPwANHMg7abzX7inrXb7zgICPx+Gp9F5+Vp7PrMRSGIU+7EHNzQ2SqBU8fvBpy+Si4NjJDMAY5deqniz8DTQBjpHcgzab8U=
before_install:
- openssl aes-256-cbc -K $encrypted_6bf1273b99ba_key -iv $encrypted_6bf1273b99ba_iv
  -in rings.tar.enc -out local.rings.tar -d
- tar xvf  local.rings.tar
script:
- sbt ++$TRAVIS_SCALA_VERSION test
after_success:
- git checkout $TRAVIS_BRANCH
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && sbt ++$TRAVIS_SCALA_VERSION
  'release with-defaults skip-tests'
