language: scala
scala:
- 2.12.7
- 2.11.12
jdk:
- oraclejdk8
ignore:
- version.sbt
- README.md
sudo: false
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.coursier"
  - "$HOME/.sbt"
env:
  global:
  - PUBLISH=true
  - secure: dDeFXT7DbUZa8nI0rRJJqXpTyZwycdObdPCooJX5MNc5TP6XpQUqodHz8wV0Yhw8ef0tofkQehVv2hHnO1gTUhllilr4C6fdPQl7pa93b7iNy4N1r/AnwESAwoKk0SWExqxPbIjHIKvcglcCbLdn6Y5407/lJ+wRTU4/A2D0hVWnxi4YDwqhvq2YI/68Q6kivaNLIQUuZ2Kud4m9nNXw5hcDMxhQYoV5uFfwpjhGSqtHncHhoeozPJGQP93ko3ScWH7/dVohlirHhnxDIIn380HAgQlw2Hh7A2rHQBrnJYWxW++rBPntqZJ9/po24JZQ/xd74U4lishmSy+uIoWnkujz5YQshnH8g2bBtMJLt34LyP9AxVjaQZZtkkp+ShyUKz+KFoJnzLKuUiPy7NcieS/Fuyxvj2eVbu5KQRudh8Lxy6WCl9OGRpbq7yt65ECfVLfncZ3rDb/w6+p1gZ4qmoWKOQW0XxdgMPhJEmKinBHyc5RAVnjLCCxO4SJ9FKmAO0CGRRdeNUKsi069lYPkFWBTJJ3r6fW09vGoe+qQjw8OliSas2fpiY8yOv1tsfbCZ4tBTVpda+zijkRjU+gDFdJ6pJwh97xn+UZTdjz1j06J/mNg7R1zgS6h+Ap3of7DHhCwSVAwHdJL/QnBUu3NLq3aIivGAanPiMXRpYBrLls=
  - secure: ivipIFC1MNht1FZTWGv8qS7s3Gas32QjOFdbRyTVrXC62lJj+uId6rsaVjrGV8q4b01suFkz5xr5ghfXUPIiV0eg+AJHrrqfa+Ovu0Da5aOx1H00erZ7yjhZeDt/Bj+J7WTN3j5opEgJKVtpj298PZwJfQghXRQGIjE/KkivPc0DI989RIaZoRxNQ4hODI6t7BRu2mlb30R7HBuXJtYIiPDF5HwhhVwa7rGRP7ngeGNE33bxP2oC7QWsLt7P+Ex7eade3WndSmWPev5NLF/L6VIf6AS4LKUcWpH3oJJ036G6dCcayD1lDLBYAaCFFazp9BGBYTQYPyyiKwRHuSohzCO9iuNVo4ro13WGq1HAYg58R6CYYjv/EESH57jm2V76okmfS7wwqLod1vtII30ZVI4ddPNvOHkQ860t8byeDG5MxBn40Z/ORyZR/fw/CaLGtDB1lEOYBuei7EnaYSVWbS/he96EIBOb+qIOpLDzbart4gfqBqevOHAW5AWtFz+ogsPdNZjTmIfAhlQ3wMO4m6n1Yut53WacD8IL7P/aE/Tq86+oyYXzNQ9JRUi//pTFW8n81MFs/7yCCnT97+PFriuo5hPeJqdE6YnKE9ofQWiABJqt2Rj8JU68OAhTpwZJ/Jv9OsmHRAqVMiAc8KKta8PW7/jaZBzBCUO6XD2J1vk=
  - secure: ovKkCEtq8JlGMgCxMpKKCVCV8hjNGzs27B3cIimoPGdOc4m6yi2bDZRlXl9EwFBkkweiYu5LsKQvo0JemNIHyt8vBzhIce0OF2gqya2Hx8/Hwqdd7WcXlP9tWqTYuwKRoouE6LaQOlAiNYz/BHF7h6YdFqBDfLV2OYAYDJRGe5dSDYv8vbuNfoD+rpwXiPAYhlzYDOrodAJrL8VqfNOP8RTWFWfbwOpkWGtx39X8J+Ypn2ed/J28Iy8LdBJ6+X0CZGYaWKlkoBmYLsvEOfxG73YFqMraWqXAXcmIiezrQVru8SMmhaZzr23I7HUs3/GAlNvcFtgjIUmCtVDQe1xRe6cO4an5Cv57iH7IUqF71ScO0+LBtE8n2XYFEk1sKEHUWIrJjd9ymrdRxFPONAdmjYVIh5dy9XVZymoDTBG2cifvyWx1+s+K0bd3k3SBieRhqxm9pMG2RcLIoyHTbT8F+VfXZSJQP3fUBym2JBRsJMaPjraY16poyPhNZXTl5sLdy8ix6WB0cKFrjzKpOto+yyvzQ+eFqaTUm/C9R3YU9ebVaFBBshGFK6ZIuJyXin0Mfs2bKzAZ4mB61KGGOK4xCddOR7NRwfrGH6Ja5vAm+xB/b4Dep4NWJZe2JiehviR7NYViGlJIQmxzEf7gqst35ejDolyIL6nwU0wnD/VBllo=
before_install:
- openssl aes-256-cbc -K $encrypted_6bf1273b99ba_key -iv $encrypted_6bf1273b99ba_iv
  -in rings.tar.enc -out local.rings.tar -d
- tar xvf  local.rings.tar
script:
- sbt ++$TRAVIS_SCALA_VERSION test
after_success:
- git checkout $TRAVIS_BRANCH
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && sbt ++$TRAVIS_SCALA_VERSION
  'release with-defaults skip-tests'
