language: scala
scala:
- 2.12.7
- 2.11.12
jdk:
- oraclejdk8
ignore:
- version.sbt
- README.md
sudo: false
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.coursier"
  - "$HOME/.sbt"
env:
  global:
  - PUBLISH=true
  - secure: ivipIFC1MNht1FZTWGv8qS7s3Gas32QjOFdbRyTVrXC62lJj+uId6rsaVjrGV8q4b01suFkz5xr5ghfXUPIiV0eg+AJHrrqfa+Ovu0Da5aOx1H00erZ7yjhZeDt/Bj+J7WTN3j5opEgJKVtpj298PZwJfQghXRQGIjE/KkivPc0DI989RIaZoRxNQ4hODI6t7BRu2mlb30R7HBuXJtYIiPDF5HwhhVwa7rGRP7ngeGNE33bxP2oC7QWsLt7P+Ex7eade3WndSmWPev5NLF/L6VIf6AS4LKUcWpH3oJJ036G6dCcayD1lDLBYAaCFFazp9BGBYTQYPyyiKwRHuSohzCO9iuNVo4ro13WGq1HAYg58R6CYYjv/EESH57jm2V76okmfS7wwqLod1vtII30ZVI4ddPNvOHkQ860t8byeDG5MxBn40Z/ORyZR/fw/CaLGtDB1lEOYBuei7EnaYSVWbS/he96EIBOb+qIOpLDzbart4gfqBqevOHAW5AWtFz+ogsPdNZjTmIfAhlQ3wMO4m6n1Yut53WacD8IL7P/aE/Tq86+oyYXzNQ9JRUi//pTFW8n81MFs/7yCCnT97+PFriuo5hPeJqdE6YnKE9ofQWiABJqt2Rj8JU68OAhTpwZJ/Jv9OsmHRAqVMiAc8KKta8PW7/jaZBzBCUO6XD2J1vk=
  - secure: rBB/DwiKe2fVzkRL+Wd9KM76tb9lltmZOc0HKHRhvhGV56bgQCHQ4T/aIyxeKsunLuZlD37VW6cxrkZG9FT8tNXXb/kcMuqYupQ8SpEo+tu9rRjHPluFi45ZnzEsZG3WPYlSFXW6t7Rb4hYVFj5ru3CXDxgOfja0+ovx/l9Msx83Gn0OSSxDuDc8mcTg7KnXJGSKW808UVZbu+CPkJpuYYP2QF6cA4hR+vliMXeRXQjDNY/fwYsLk2J4T2NQ0O/u4qhH6V1Evq5pekY0p8wh1Jlm8v8iqCogooLSnT+QvCHvHFBrlx+YMQL46xnmJk6zTbTEmMwjzTt0lwUIw5mf9TCKjQdNt4L96/woFTutm/3SFN0Ol/X9m+zI/ROr+CuCRXnf/KISaM/YnRDaxqUt0O0XVUjOfSOQ2u88Rjqa3iYqssHqaZ4vGzrOzIhpeP/wJswpfPsh5iKRM7/L8rwm7FOnON8u6OAt6q9z3kCHwbyUGms0u/8BXjWk9hnUziKG5kSajTlyXVQwdF/0GlseBG/4w++FtwJODmTK6NK6ZN0mb0bMpDnxHF7jJM4crKo68UlNXroWokXnTPwANHMg7abzX7inrXb7zgICPx+Gp9F5+Vp7PrMRSGIU+7EHNzQ2SqBU8fvBpy+Si4NjJDMAY5deqniz8DTQBjpHcgzab8U=
  - secure: Qc1w/Bz/MmsP8jMmO5D+eBxY8q6aVHBuGasKF8Zr96+8tYiz+uSZGz6oBDI0W9KEDeSuiKpJaUpi6uHYFtEeM9Z7sZkvm5qdcket8rQzlV6mA5PBcEAJPaTuehKSxE96h/kYI0mXqX2Ll1LpJbo2w32WldAxFJcocVwr1YDpPc8b2BzFF+99IBuvdbtWQFlYXB9zdoRDKPym0Y/7Ya9PZVYY0jS38fFEL4sabdPdV6Kk59MVS6aD5PsI6Bn0eRchFXNBjdtxKkjqnkGrjZbMy2s6V7b2SY2aoayOpSkhx2hCkiQk7SQgXEvhmeJ5gx679nBtYdtIp3wYPdGl6Hba0uaIaCKivO+b3TVVn4I5XYtRRb7qkvGLBATsLM4zbL2WfsfXkZepiMCOoxXDZpW7zqKs9z6P5Reggm5EvfC0t+75pd5MfG7oSbzdQIo2EISu/q5OW7V789jAoasr6EuHrNmMW73YkhfFP6yGgwmYC4wKwQf8TFCb0/n8W5qcGnk3FUT25u2TY/yScPr9g9dAWFNDS0zxzmLB3vBAPnoqCgHiJ7HG8ruUM9KFhUWDwnEIl86rm98c9y482cbkBTP3En895lA/bxwbMeNCHSQySzErqau+98C+LAmNDf+eKDWq4ukG3Zhnng+cw/4GbiKKmL+1bay7t7zkJgMcjTMrHgk=
before_install:
- openssl aes-256-cbc -K $encrypted_6bf1273b99ba_key -iv $encrypted_6bf1273b99ba_iv
  -in rings.tar.enc -out local.rings.tar -d
- tar xvf  local.rings.tar
script:
- sbt ++$TRAVIS_SCALA_VERSION test
after_success:
- git checkout $TRAVIS_BRANCH
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && sbt ++$TRAVIS_SCALA_VERSION
  'release with-defaults skip-tests'
